# Copyright (C) 2008-2010, Sebastian Riedel.

=head1 NAME

Mojolicious::Guides::FAQ - Чатсто Задаваемые Вопросы

=head1 ОПИСАНИЕ

Этот документ содержит самые часто задаваемые вопросы о
L<Mojolicious>, а так же правильные ответы на них.

=head1 ВОПРОСЫ

=head2 Я думаю, что L<Mojolicious> потрясающий. Как я могу поддержать вас, парни?

Пишите о фреймворке в своем блоге или твиттере. Притягивайте новых людей! :)

=head2 Кажется, я нашел баг. Что я могу сделать?

Подготовьте тест для демонстрации ошибки. Вы вряд ли сможете самостоятельно исправить баг, однако, постарайтесь, чтобы разработчики смогли разобраться в проблеме.
Отправка Вашего приложения полностью принесет скорее больше вреда, чем пользы.
Папка C<t> в дистрибутиве содержит много хороших примеров того, как правильно создавать тесты.
Написание теста обычно является сложнейшим, но лучшим этапом исправления ошибки, который поможет быстрее решить проблему. ;)

Теперь Вы готовы к общению с разработчиками через GitHub
(http://github.com/kraih/mojo), почтовые рассылки
(L<http://groups.google.com/group/mojolicious>) или IRC
(C<#mojo> on C<irc.perl.org>).

Если Вы решили исправить ошибку самостоятельно, обязательно ознакомьтесь с
L<Mojolicious::Guides::CodingGuidelines> тоже.

=cut
